// Topic pages own shared prose; the manifest owns navigation and project status.
// Generated HTML is committed so the site still works without a server/build tool.
// Default: verify. --write: update derived regions and navigation.
const fs = require('node:fs');
const path = require('node:path');
const root = path.resolve(__dirname, '..', 'docs');
const read = file => fs.readFileSync(path.join(root, file), 'utf8').replace(/\r\n/g, '\n');
const manifest = JSON.parse(read('content/learning.json'));
const write = process.argv.includes('--write');
const escape = s => s.replaceAll('&', '&amp;').replaceAll('<', '&lt;').replaceAll('>', '&gt;').replaceAll('"', '&quot;');
const errors = [];
let regions = 0;
function update(file, after) {
  if (read(file) === after.replace(/\r\n/g, '\n')) return;
  if (write) fs.writeFileSync(path.join(root, file), after);
  else errors.push(file + ' is stale; run node scripts/build-docs.cjs --write');
}
const topics = manifest.topics;
const ids = new Map(topics.filter(t => t.id).map(t => [t.id, t]));
if (ids.size !== topics.filter(t => t.id).length) throw Error('Duplicate topic ID');
for (const [name, route] of Object.entries(manifest.routes)) {
  if (new Set(route).size !== route.length) throw Error('Duplicate route step: ' + name);
  for (const id of route) if (!ids.has(id)) throw Error('Unknown route step: ' + id);
}
for (const topic of ids.values()) {
  if (!fs.existsSync(path.join(root, topic.file))) throw Error('Missing topic: ' + topic.file);
  for (const id of topic.prerequisites || []) if (!ids.has(id)) throw Error('Unknown prerequisite: ' + id);
  if (topic.id === 'ray-tracing') topic.blurb = manifest.project.rayTracing;
}
function visit(id, trail = []) {
  if (trail.includes(id)) throw Error('Prerequisite cycle: ' + [...trail, id].join(' -> '));
  for (const pre of ids.get(id).prerequisites || []) visit(pre, [...trail, id]);
}
for (const id of ids.keys()) visit(id);
// Reference codes stay stable; visible core step numbers follow the route.
const core = manifest.routes.core;
const sidebarCore = topics.filter(t => core.includes(t.id)).map(t => t.id);
if (JSON.stringify(sidebarCore) !== JSON.stringify(core)) throw Error('Sidebar order differs from the core route');
let part = '';
const parts = new Map();
for (const topic of topics) {
  if (topic.part) part = topic.part;
  else parts.set(topic.id, part);
}
for (const [index, id] of core.entries()) {
  for (const pre of ids.get(id).prerequisites || []) {
    if (core.indexOf(pre) < 0 || core.indexOf(pre) >= index) throw Error(id + ': prerequisite follows the lesson: ' + pre);
  }
  if (id !== 'start') ids.get(id).step = String(index).padStart(2, '0');
}
update('assets/topics.js', '/* Generated by scripts/build-docs.cjs; edit docs/content/learning.json. */\n' +
  'window.KYTY_TOPICS = ' + JSON.stringify(topics, null, 2) + ';\n' +
  'window.KYTY_ROUTES = ' + JSON.stringify(manifest.routes, null, 2) + ';\n' +
  'window.KYTY_PROJECT = ' + JSON.stringify(manifest.project, null, 2) + ';\n');
const sources = new Map();
for (const file of fs.readdirSync(root).filter(f => f.endsWith('.html'))) {
  const html = read(file);
  for (const match of html.matchAll(/<p\b[^>]*data-shared="([^"]+)"[^>]*>[^]*?<\/p>/g)) {
    const key = file + ':' + match[1];
    if (sources.has(key)) throw Error('Duplicate shared source: ' + key);
    sources.set(key, match[0].replace(/ data-shared="[^"]+"/, ''));
  }
}
for (const file of fs.readdirSync(root).filter(f => f.endsWith('.html'))) {
  // Preserve existing line endings outside generated regions.
  let after = fs.readFileSync(path.join(root, file), 'utf8');
  const topic = topics.find(t => t.file === file);
  if (topic && topic.step) {
    const code = /^[BCD]\d+$/.test(topic.n) ? ' · ' + topic.n : '';
    const label = 'Step ' + topic.step + ' · ' + parts.get(topic.id) + code;
    if (!after.includes('class="topic-eyebrow"')) throw Error(file + ': missing core lesson label');
    after = after.replace(/(<p class="topic-eyebrow">)[^]*?(<\/p>)/,
      (_, open, close) => open + escape(label) + close);
  }
  after = after.replace(/<!-- shared:([^ ]+) -->([^]*?)<!-- \/shared -->/g, (_, key) => {
    if (!sources.has(key)) throw Error('Missing shared source: ' + key);
    const sourceFile = key.split(':')[0];
    const body = sources.get(key).replace(/href="#/g, 'href="' + sourceFile + '#');
    regions++;
    return '<!-- shared:' + key + ' -->\n' + body + '\n<!-- /shared -->';
  });
  after = after.replace(/<!-- code:(labs\/beginner\/[\w.-]+\.cpp) -->([^]*?)<!-- \/code -->/g, (_, source) => {
    regions++;
    return '<!-- code:' + source + ' -->\n<pre data-lang="cpp"><code>' + escape(read(source).trimEnd()) + '</code></pre>\n<!-- /code -->';
  });
  after = after.replace(/<!-- output:(labs\/beginner\/[\w.-]+\.txt) -->([^]*?)<!-- \/output -->/g, (_, source) => {
    regions++;
    return '<!-- output:' + source + ' -->\n<pre data-lang="text">' + escape(read(source).trimEnd()) + '</pre>\n<!-- /output -->';
  });
  after = after.replace(/<!-- prerequisites:([\w-]+) -->([^]*?)<!-- \/prerequisites -->/g, (_, id) => {
    if (!ids.has(id)) throw Error('Unknown prerequisite owner: ' + id);
    const topic = ids.get(id);
    const links = (topic.prerequisites || []).map(pre => {
      const item = ids.get(pre);
      return '<a href="' + escape(item.file) + '">' + escape(item.title) + '</a>';
    });
    const body = '<p class="lesson-prerequisites"><strong>Before this page:</strong> ' +
      (links.length ? links.join(' · ') : 'no prior C++ or emulation knowledge required') +
      '. <a href="start.html">View the learning route</a>.</p>';
    regions++;
    return '<!-- prerequisites:' + id + ' -->\n' + body + '\n<!-- /prerequisites -->';
  });
  after = after.replace(/<!-- project:(rayTracing|revision) -->([^]*?)<!-- \/project -->/g, (_, key) => {
    const value = key === 'revision' ? manifest.project.revision + ' (' + manifest.project.date + ')' : manifest.project[key];
    regions++;
    return '<!-- project:' + key + ' -->' + escape(value) + '<!-- /project -->';
  });
  update(file, after);
}
if (errors.length) { console.error(errors.join('\n')); process.exitCode = 1; }
else console.log((write ? 'Updated' : 'PASS:') + ' navigation, prerequisite graph and ' + regions + ' generated prose/code/status regions.');
