execute_process(COMMAND "${PROGRAM}" RESULT_VARIABLE result OUTPUT_VARIABLE actual ERROR_VARIABLE error)
if(NOT "${result}" STREQUAL "0")
  message(FATAL_ERROR "Program failed (${result}): ${error}\n${actual}")
endif()
file(READ "${EXPECTED}" expected)
string(REPLACE "\r\n" "\n" actual "${actual}")
string(REPLACE "\r\n" "\n" expected "${expected}")
if(NOT "${actual}" STREQUAL "${expected}")
  message(FATAL_ERROR "Output differs.\nExpected:\n${expected}\nActual:\n${actual}")
endif()
